name: Continuous integration test suite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download FFmpeg
        run: |
          mkdir -p $HOME/ffmpeg
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ffmpeg-release-amd64-static.tar.xz -C $HOME/ffmpeg --strip-components=1
  
      - name: Add FFmpeg to PATH
        run: echo "PATH=$HOME/ffmpeg:$PATH" >> $GITHUB_ENV

      - name: Verify FFmpeg installation
        run: ffmpeg -version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pip install --upgrade pipenv
          pipenv install

      - name: Run MPy3.py
        env:
            DISCOGS_USER_TOKEN: ${{ secrets.DISCOGS_USER_TOKEN }}
        run: |
            pipenv run python MPy3.py
        working-directory: /
